#
#   BetterKeepInventory By BeepSterr
#   Version 1.6
#
#   SpigotMC:         https://www.spigotmc.org/resources/betterkeepinventory.93081/
#   Documentation:    https://beeps.notion.site/Better-Keep-Inventory-f5d49a15a8174ce598bbb876d3003e46
#   GitHub:           https://github.com/Awoo-industries/BetterKeepInventory
#   Discord:          https://leafcat.live/discord
#

main:

  # Quick way to turn off ALL functionality.
  enabled: true

  # When enabled will spam the console with debugging data.
  # Should only be enabled if asked by the developer
  debug: false

  # Used internally to determine if migrations need to happen
  # You should __NEVER__ have to change this. (And you might break it if you do)
  config_version: 4

  # Allows users to have a "grace period" after dying where they wont be affected by the plugin
  # in seconds (300 = 5 minutes) set to 0 to disable
  grace: 0

items:

  hotbar:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Any item with a custom name that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_name: "NONE"

    # Any item with a custom lore that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_lore: "NONE"

    # Materials in this list will be ignored
    # Use names from this list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - SHEARS
      - FISHING_ROD
      - CARROT_ON_A_STICK
      - FLINT_AND_STEEL
      - WARPED_FUNGUS_ON_A_STICK

  inventory:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Any item with a custom name that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_name: "NONE"

    # Any item with a custom lore that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_lore: "NONE"

    # Materials in this list will be ignored
    # Use names from this list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - SHEARS
      - FISHING_ROD
      - CARROT_ON_A_STICK
      - FLINT_AND_STEEL
      - WARPED_FUNGUS_ON_A_STICK

  armor:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Any item with a custom name that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_name: "NONE"

    # Any item with a custom lore that includes this text will be ignored and left alone. set to "NONE" to disable.
    ignored_lore: "NONE"

    # Materials in this list will be ignored
    # Use names from this list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - ELYTRA
exp:

  levels:
    # Sets the mode used for calculating exp loss
    # Valid options are:
    # "NONE"          Do not lose levels on death.
    # "ALL"           Lose all levels
    # "SIMPLE"        Lose a set amount of levels between min and max (min and max are numbers)
    # "PERCENTAGE"    Lose a percentage of levels between min and max (min and max are percentages)
    mode: "NONE"
    min: 0
    max: 0

  # Decides if progress towards next level will be lost
  reset_level: false

hunger:
  # Sets the mode used for calculating hunger on respawn
  # Valid options are:
  # "NONE"          Use vanilla behavoir of getting full hunger on death
  # "KEEP"          Keep current hunger level, but clamp value between min and max
  mode: "KEEP"
  min: 8  # 6 = 3 Drumsticks  (can't sprint)
  max: 20  # 20 = 10 Drumsticks (max)
  extra_removed_on_death: 1 # Extra hunger lost for dying (Will be applied BEFORE clamping)


potions:

  # These potion effects will be kept on death
  # If you want to disable potion keeping, Make this list empty.
  kept_effects:
    - ABSORPTION
    - BAD_OMEN
    - BLINDNESS
    - DAMAGE_RESISTANCE
    - FAST_DIGGING
    - FIRE_RESISTANCE
    - HERO_OF_THE_VILLAGE
    - INCREASE_DAMAGE
    - INVISIBILITY
    - JUMP
    - LUCK
    - NIGHT_VISION
    - REGENERATION
    - SLOW_FALLING
    - WATER_BREATHING
    - WEAKNESS
    - UNLUCK
    - SLOW

  # Max length a effect will have when respawned
  # (if it has 2 minutes and this is set to 30, you will respawn with 30 seconds of the effect)
  # set to "false" to disable this, and keep orginal effect length
  max_duration: 30

  # Levels to reduce the effect by
  # If this is set to 2 Speed IV will become Speed II
  reduce_potency: 1


# Requires Vault
eco:

  # economy features are enabled/disabled?
  enabled: false

  # Sets the mode used for calculating economy lost
  # Valid options are:
  # "SIMPLE"          Lose a set amount on death
  # "PERCENTAGE"      Lose a percentage of the current balance
  mode: "SIMPLE"

  # Amount of money lost on death (Or the percentage if percentage mode is used)
  amount: 0

  # if set to a positive number, the amount taken is limited to this (only useful when percentage mode is used)
  max_amount: -1

  # Minimum balance of the player, if the player has less than this amount they will not be charged.
  min_balance: 0

  # If enabled, the balance lost is paid out to the killer of the player
  # Only applicable in PvP Situations!
  pay_to_killer: false

overrides:

  # Overrides allow you to disable specific punishments based on conditions like world.
  #

  worlds:

    # You can use ALL to disable everything, or NONE to disable nothing. ITEMS also works to combine HOTBAR, INVENTORY and ARMOR
    # You can use damage types to customize the death types to punish https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    world_no_pvp:
      damage_types:
        # This example disables item & hunger damage in the world "world_no_pvp" if the death was caused by pvp
        PVP:     # A Custom "PVP" damage type also exists.
          - ITEMS

    # This exmple completely disables the plugin in "world_disabled"
    # Not specifying a damage type always applies it (in that world).
    world_disabled:
      - ALL

    # This exmple disables exp loss in "world_disabled"
    world_no_exp_loss:
      - EXP
      - EXP_LEVEL


  # https://www.spigotmc.org/resources/towny-advanced.72694/
  towny:

    enabled: false
    towns:

      # Disable nothing in unclaimed area.
      wilderness:
        - NONE
      # Disable economy loss when a player dies in any town
      any_town:
        - ECO
      # Disables everything if player dies in town they are a member of
      player_town:
        - ALL
      # You can also specify a town name to use
      'North Appletown':
        - ITEMS
        - HUNGER

    nations:
      # Disable economy loss when a player dies in any town
      any_nation:
        - ECO
      # Disables everything if player dies in town they are a member of
      player_nation:
        - NONE
      # You can also specify a town name to use
      'The Empire':
        - ITEMS
        - HUNGER

  grief_prevention:

    enabled: false
    claims:
      own:    # Claims owned by the user
        - ALL
      admin:    # Admin claims
        - NONE
      edit:   # Claims where the user has "edit" permission
        - NONE
      build:   # Claims where the user has "build" permission
        - NONE
      inventory:   # Claims where the user has "inventory" permission
        - NONE
      access:   # Claims where the user has "access" permission
        - NONE
      manage:   # Claims where the user has "manage" permission
        - NONE
      any:   # Any claim
        - NONE