# Configuration for BetterKeepInventory plugin
version: "2.0"
hash: "abc123"
debug: true

default_behavior: "DROP"

rules:
  1:
    name: "Default"
    enabled: true
    conditions:
      permission:
        - "!player.keepinventory"
      world:
        - "*"
    drop:
      mode: "ALL"
      affects:
        - "IRON_INGOT"
        - "DIAMOND"
      with_lore:
        - ".*Kept on Death.*"
      with_name:
        - "Soundbound"