#
#   BetterKeepInventory By BeepSterr
#   Version 1.3
#
#   https://www.spigotmc.org/resources/betterkeepinventory.93081/
#

main:

  # Quick way to turn off ALL functionality.
  enabled: true

  # When enabled will spam the console with debugging data.
  debug: false

  # Used internally to determine if migrations need to happen
  # You should __NEVER__ have to change this. (And you might break it if you do)
  config_version: 2

items:

  all:
    # should we look for breakable items in Shulker Boxes (May cause lag)?
    deep_search: false

  hotbar:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Items containing given text will be ignored:
    # (set to "NONE" to not use this feature
    name: "NONE"
    lore: "Unbreakable"

    # Materials in this list will be ignored
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - SHEARS
  inventory:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Items containing given text will be ignored:
    # (set to "NONE" to not use this feature
    name: "NONE"
    lore: "Unbreakable"

    # Materials in this list will be ignored
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - SHEARS

  armor:
    # Sets the mode used for calculating damage dealt
    # Valid options are:
    # "NONE"          Ignores items in this section (disables)
    # "SIMPLE"        Deals a set amount of damage between min and max
    # "PERCENTAGE"    Deals a percentage of the items durability based on min and max
    mode: "NONE"
    min: 0
    max: 0

    # Should enchantments like Unbreaking affect the damage dealt?
    use_enchantments: true

    # Should we always leave at least 1 use left on items?
    dont_break: true

    # Items containing given text will be ignored:
    # (set to "NONE" to not use this feature
    name: "NONE"
    lore: "Unbreakable"

    # Materials in this list will be ignored
    # Example:
    # - GOLDEN_HELMET
    # - GOLDEN_CHESTPLATE
    ignored_materials:
      - SHEARS
exp:

  levels:
    # Sets the mode used for calculating exp loss
    # Valid options are:
    # "NONE"          Do not lose levels on death.
    # "ALL"           Lose all levels
    # "SIMPLE"        Lose a set amount of levels between min and max (min and max are numbers)

    # "PERCENTAGE"    Lose a percentage of levels between min and max (min and max are percentages)
    mode: "NONE"
    min: 0
    max: 0

  # Decides if progress towards next level will be lost
  reset_level: false

hunger:
  # Sets the mode used for calculating hunger on respawn
  # Valid options are:
  # "NONE"          Use vanilla behavoir of getting full hunger on death
  # "KEEP"          Keep current hunger level, but clamp value between min and max
  mode: "NONE"
  min: 6  # 6 = 3 Drumsticks  (can't sprint)
  max: 20  # 20 = 10 Drumsticks (max)


potions:

  # These effects will be kept on death
  kept_effects:
    - ABSORPTION
    - BAD_OMEN
    - BLINDNESS
    - DAMAGE_RESISTANCE
    - FAST_DIGGING
    - FIRE_RESISTANCE
    - HERO_OF_THE_VILLAGE
    - INCREASE_DAMAGE
    - INVISIBILITY
    - JUMP
    - LUCK
    - NIGHT_VISION
    - REGENERATION
    - SLOW_FALLING
    - WATER_BREATHING
    - WEAKNESS
    - UNLUCK
    - SLOW

  # Max length a effect will have when respawned
  # (if it has 2 minutes and this is set to 30, you will respawn with 30 seconds of the effect)
  max_duration: 30

  # Levels to reduce the effect by
  # If this is set to 2 Speed IV will become Speed II
  reduce_potency: 30

  # Should the reduce & duration rule apply to negative effects?
  reduce_negative: false


# Requires Vault
eco:

  # Amount of money lost on death
  amount: 0