# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java16:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
        
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with: 
          name: plugin
          path: |
            /home/runner/work/BetterKeepInventory/BetterKeepInventory/target/*.jar
            !/home/runner/work/BetterKeepInventory/BetterKeepInventory/target/original-*.jar
  build-java11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
        
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with: 
          name: plugin
          path: |
            /home/runner/work/BetterKeepInventory/BetterKeepInventory/target/*.jar
            !/home/runner/work/BetterKeepInventory/BetterKeepInventory/target/original-*.jar
  build-java8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
        
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with: 
          name: plugin
          path: |
            /home/runner/work/BetterKeepInventory/BetterKeepInventory/target/*.jar
            !/home/runner/work/BetterKeepInventory/BetterKeepInventory/target/original-*.jar
