# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Test Build

on:
  - push
  - workflow_dispatch
jobs:

  build-jars:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Rename File
        run: mv ./target/BetterKeepInventory-*.jar ./target/build.jar

      - name: Post build to discord
        run: "curl -F 'payload_json={\"username\": \"BetterKeepInventory\", \"content\": \"[${{ github.sha }}](https://github.com/beepsdev/BetterKeepInventory/commit/${{ github.sha }}) ${{github.event.head_commit.message}}\"}' -F \"build.jar=@./target/build.jpg\" ${{ secrets.DISCORD_BUILD_WEBHOOK }}"

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./target/build.jar
