# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Development Build

on:
  push:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:

  build-jars:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean validate package install

      - name: Rename Jar (Plugin)
        run: mv ./plugin/target/BetterKeepInventory-*.jar ./BetterKeepInventory.jar

      - name: Rename Jar (API)
        run: mv ./api/target/BetterKeepInventory-*.jar ./BetterKeepInventory-api.jar

      - name: Publish artifact (Plugin)
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: ./BetterKeepInventory.jar

      - name: Publish artifact (API)
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: ./BetterKeepInventory-api.jar
