name: Nightly Snapshot Build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'plugin/**'
      - 'api/**'
      - '.github/workflows/build.yml'
      - 'pom.xml'
#  schedule:
#    - cron: '0 10 * * *' # Every day at 10AM UTC
  workflow_dispatch:

jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Generate unique snapshot version
        id: versioning
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          SNAPSHOT_TAG="SNAPSHOT"
          BUILD_COUNT=$(date +%s | cut -c7-) # Small unique number
          VERSION="${BASE_VERSION}-${SNAPSHOT_TAG}-${BUILD_COUNT}"

          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set version in all modules
        run: |
          mvn versions:set -DnewVersion=${{ steps.versioning.outputs.version }} -DgenerateBackupPoms=false

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Rename JAR
        run: |
          mkdir out
          mv ./plugin/target/BetterKeepInventory-*.jar ./out/BetterKeepInventory-${{ steps.versioning.outputs.version }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterKeepInventory-${{ steps.versioning.outputs.version }}
          path: ./out/BetterKeepInventory-${{ steps.versioning.outputs.version }}.jar
