# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Test Build

on:
  - push
  - workflow_dispatch
jobs:

  build-jars:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Rename File
        run: mvn --batch-mode --update-snapshots verify

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin-JDK16
          path: |
            /home/runner/work/BetterKeepInventory/BetterKeepInventory/target/BetterKeepInventory-*.jar

      - name: Publish build to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_BUILDS_ID }}
          webhook_token: ${{ secrets.DISCORD_BUILDS_TOKEN }}
          message: "[${{ github.sha }}](https://github.com/beepsdev/BetterKeepInventory/commit/${{ github.sha }}) ${{github.event.head_commit.message}}"
          file: ./target/BetterKeepInventory-*.jar