# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Development Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:


  build-jars:

    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Rename File
        run: mv ./target/BetterKeepInventory-*.jar ./target/dev-build.jar

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./target/dev-build.jar
