name: Deploy to GitHub Packages

on:
  workflow_dispatch:
  push:
#    tags:
#      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Publish with Maven
        run: |
          mvn clean install
          cd api
          mvn deploy -Dgpg.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
